[conda]
packages = ["python=3.6","svgpathtools","numpy-stl","matplotlib","scipy","ipdb","vtk"]
channels = ["conda-forge"]

[pip]
packages = ["numpy"]
# indexes = [...]

[script]
# expr = "some_julia_expression()"
# file = "/path/to/julia/script.jl"